### ISSUE TITLE
DELETE operation never worked?

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-lsc#13]
## Why
Today I wrote an Integration test for **DELETE** operation for forward and address mapping sync, but it did not work.

I try to write the same IT for User sync (cc @vttranlina) but the **DELETE** operation does not work as well. I doubt the same issue for Alias sync (which has been written longgg time ago by Remi).

The test case for User DELETE:
```java
    @Test
    void lscJobShouldRemoveAllDanglingUserInJames() {
        createUser("onlyexistinginjames@james.org");

        // Should be only onlyexistinginjames@james.org at this moment
        given(requestSpecification)
            .get("/users").prettyPeek()
        .then()
            .statusCode(HttpStatus.SC_OK);

        // Run the LSC user sync job (onlyexistinginjames@james.org is not in the LDAP entries)
        runLscContainer();

        // THEN the user onlyexistinginjames@james.org should be deleted out of James. => But it actually does not.
        await.untilAsserted(() -> assertThatCode(() -> {
            String response = given(requestSpecification)
                .get("/users").prettyPeek()
            .then()
                .statusCode(HttpStatus.SC_OK)
                .extract()
                .jsonPath()
                .getString("");

            assertThat(response).doesNotContain("onlyexistinginjames@james.org");
        }).doesNotThrowAnyException());
    }
```

Quickly check the LSC logs, it seems there is no call to `getListPivots` (to James), no  `getBean` call for `onlyexistinginjames@james.org`, and therefore not even a **DELETE** operation is being triggered...

My impression is that LSC only gets the pivot list on LDAP, and does not care about pivots on James. That would be breaking our knowledge about LSC since then.

TODO investigate and try to fix this.

## DoD
Either this is fixed or if that is a LSC limitation -> adapt the DELETE operation in Readme so it does not lead to any confusion.

**Comment by Arsnael** [comment]
Might need a bit more thoughts depending on the situation, but I'm not sure that we want the DELETE operation, at least for the user.

In an organization for example, at least might need retention of data for some time, even if the user has been removed from it (like if police requests access for example). In a SaaS setup thought, with GDPR, might make sense though... Honestly I'm not sure we should do a delete based on a lsc script. In case it's really needed, we do have webadmin task for it now? 

It's likely a debate honestly

**Comment by quantranhong1999** [comment]
I agree with you on the legal aspect. Here the issue is only about technical detail regarding LSC functionality. If we don't want LSC to delete the users, we can :-)

**Comment by Arsnael** [comment]
That's true, you can always decide to use it or not! Fair point then!

**Comment by quantranhong1999** [comment]
LSC fix (just need to add a missing options though): https://github.com/linagora/tmail-lsc/pull/19
Helm TMail backend: https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/16/diffs
