### ISSUE TITLE
[MU] LSC job to synchronize quota size for users

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-lsc#21]
## Why

As of now, the Python engine that is used to sync (users, aliases, quotas) is not reliable.

We need to rely on the LSC script. We are missing the quota size sync job.

## How

Read the `mailQuotaSize` value from LDAP and sync it to TMail
<img width="414" alt="image" src="https://github.com/user-attachments/assets/06c91965-883b-4b28-b65a-44203dc6abe0">

For the LSC job:
- pivot: list users API
- API to get quota size of a user: `curl -XGET http://ip:port/quota/users/{usernameToBeUsed}/size`
- API to create/update quota size for a user: `curl -XPUT http://ip:port/quota/users/{usernameToBeUsed}/size`
- API to delete quota size for a user: `curl -XDELETE http://ip:port/quota/users/{usernameToBeUsed}/size`

## DoD
code + unit tests + integration test + sample configuration + README.

cc @chibenwa

**Comment by chibenwa** [comment]
Thanks a lot @quantranhong1999

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-lsc/pull/22
